services:
  ros-player:
    container_name: ros-player
    build: server
    image: ros-player
    volumes:
      - ./bags:/bags/bags:ro
      - ./../../src/main/resources:/bags/resources:ro
    ports:
      - "9090:9090"
      - "9091:9091"
      - "4000:4000"
