services:
  carla:
    image: carlasim/carla:0.10.0
    restart: unless-stopped
    runtime: nvidia
    ports:
      - "10200:2000"  # CARLA RPC port
      - "10201:2001"  # CARLA streaming port
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    command: bash CarlaUnreal.sh -RenderOffScreen -nosound
  carla-visualizer:
    image: mjxu96/carlaviz
    ports:
      - "10301:8080"  # Frontend UI
      - "10302:8081"  # Backend websocket stream
      - "10303:8089"  # Backend REST API
    command: ["/bin/bash", "./docker/run.sh", "--simulator_host", "carla", "--simulator_port", "2000"]
    restart: unless-stopped
    depends_on:
      - carla
  carla-test-client:
    build:
      context: .
    depends_on:
      - carla
